name: 'Test'
on: [pull_request, push]

jobs:
  swig:
    runs-on: ubuntu-latest
    name: Generate the SWIG wrappers ${{ matrix.no_async }}

    strategy:
      fail-fast: false
      matrix:
        no_async: ['', '-no_async']

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: mmomtchev/setup-swig@main
      with:
        branch: jse

    - name: Verify SWIG
      run: swig-jse -version

    - name: Run SWIG to generated the wrappers
      run: npm run swig
      env:
        SWIG_FEATURES: ${{ matrix.no_async && '-DNO_ASYNC' || '' }}

    - name: Upload SWIG-generated wrappers
      uses: actions/upload-artifact@v4
      with:
        name: swig-generated${{ matrix.no_async }}
        path: |
          build/*

  
  build-native:
    runs-on: ${{ matrix.platform }}
    name: Build native ${{ matrix.platform }}${{ matrix.no_async }}
    needs: swig

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        no_async: ['', '-no_async']

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # From https://gist.github.com/geoffreygarrett/06765936df5b4687d320491517ca5d47
    # This is ugly and it is going away as soon as possible
    - name: Setup PkgConfig (Windows)
      if: runner.os == 'Windows'
      env:
        PKG_CONFIG_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip"
        GETTEXT_RUNTIME_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip"
        GLIB_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip"
      run: |
        curl -LO "${{ env.PKG_CONFIG_ZIP }}"
        7z x pkg-config_0.26-1_win32.zip -oC:\MinGW\bin pkg-config.exe
        curl -LO "${{ env.GETTEXT_RUNTIME_ZIP }}"
        7z x gettext-runtime_0.18.1.1-2_win32.zip -oC:\MinGW\bin intl.dll
        curl -LO "${{ env.GLIB_ZIP }}"
        7z x glib_2.28.8-1_win32.zip -oC:\MinGW\bin libglib-2.0-0.dll
        echo "C:\MinGW\bin" >> $GITHUB_PATH
        dir /s \MinGW

    - name: Download the SWIG-generated wrappers
      uses: actions/download-artifact@v4
      with:
        name: swig-generated${{ matrix.no_async }}
        path: build
        
    - name: Install dependencies
      run: |
        npm install --ignore-scripts
        npx xpm install

    - name: Build the native version
      run: npm run build:native
      env:
        HADRON_OPTS: -Dwith_zlib=true ${{ matrix.no_async && '-Dno_async=true' || '' }}
    
    - name: Upload native artifact ${{ matrix.platform }}
      uses: actions/upload-artifact@v4
      with:
        name: native-${{ matrix.platform }}${{ matrix.no_async }}
        path: lib/binding/*
